version: '3'

services:
  backend:
    platform: linux/amd64
    build:
      context: ./backend/ca2_project
    command: gunicorn ca2_project.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    platform: linux/amd64
    build:
      context: ./frontend/ca2-client
    volumes:
      - react_build:/ca2-client/build
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/ca2-client
    depends_on:
      - backend
      - frontend
volumes:
  react_build: