# Generated by Django 4.0.8 on 2022-11-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_remove_worldborder_area_remove_worldborder_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldborder',
            name='adderuser',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
