# Generated by Django 4.1.1 on 2022-11-05 20:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_remove_worldborder_fips_remove_worldborder_iso2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldborder',
            name='area',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='mpoly',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='region',
        ),
        migrations.AddField(
            model_name='worldborder',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
